- src/anaconda-postgres/devcontainer-template.json
- src/miniconda-postgres/devcontainer-template.json
Addresses - https://github.com/devcontainers/templates/issues/33
> Updates description of Templates

- src/dotnet/devcontainer-template.json
Addresses - https://github.com/devcontainers/templates/issues/38
Depends upon -
- https://github.com/devcontainers/images/pull/201
> dotnet -Update proposals (adds 7)

- src/dotnet-mssql/devcontainer-template.json
- src/dotnet-postgres/devcontainer-template.json
Updates .NET default version to 7 and add more version proposals.
> dotnet-mssql & dotnet-postgres: Update to .NET 7

- src/javascript-node-mongo/README.md
From https://github.com/microsoft/vscode-docs/pull/5782#discussion_r1023153821, we discussed MongoDB should be one word. Also fixed another typo.
> Update MongoDB README.md

- src/rust/devcontainer-template.json
Addresses - https://github.com/devcontainers/templates/issues/58
> Rust: Use bullseye as default

- .devcontainer/devcontainer.json
- src/kubernetes-helm-minikube/.devcontainer/devcontainer.json
- src/kubernetes-helm-minikube/devcontainer-template.json
Related to https://github.com/devcontainers/features/pull/314
> Update docker-in-docker version

- src/docker-in-docker/.devcontainer/devcontainer.json
- src/docker-in-docker/devcontainer-template.json
Fixes: https://github.com/devcontainers/templates/issues/73
> docker-in-docker: fix bug - Incorrect Feature reference

- src/ruby-rails-postgres/.devcontainer/docker-compose.yml
I'm still learning my way around Docker and so it took me a little while to work out what you're meant to do once you've applied this template in a Codespace: set your `config/database.yml` and then start your app (and that's it!). Hopefully this helptext makes it a bit more clear for others.
> Rails: helptext on how to connect to DB

- src/php-mariadb/devcontainer-template.json
- src/php/devcontainer-template.json
From: https://github.com/devcontainers/images/issues/90
> PHP: Update image variant proposals - add 8.2 & EOL 7.4

- src/alpine/devcontainer-template.json
Details - https://github.com/devcontainers/images/issues/90
> Alpine: Update image variant proposals - add 3.17

- src/docker-in-docker/NOTES.md
- src/docker-outside-of-docker-compose/.devcontainer/devcontainer.json
- src/docker-outside-of-docker-compose/devcontainer-template.json
- src/docker-outside-of-docker/.devcontainer/devcontainer.json
- src/docker-outside-of-docker/devcontainer-template.json
- src/kubernetes-helm/.devcontainer/devcontainer.json
- src/kubernetes-helm/devcontainer-template.json
Ref: https://github.com/devcontainers/features/pull/373
> Templates: Rename "docker-from-docker" to "docker-outside-of-docker"

- src/powershell/.devcontainer/devcontainer.json
- src/powershell/devcontainer-template.json
Ref : https://github.com/devcontainers/features/pull/326
> Powershell: Bump version of 'common-utils' Feature

- src/dotnet-mssql/NOTES.md
The previous notes mentioned PostgresSql and Go.
> Corrected the database name and container type

- src/docker-existing-docker-compose/.devcontainer/docker-compose.yml
- src/docker-existing-docker-compose/devcontainer-template.json
Fixes microsoft/vscode-remote-release#7946
> Paths are relative to first docker-compose.yml

- src/rust/.devcontainer/devcontainer.json
- src/rust/devcontainer-template.json
> [Rust] Add note about Cargo cache persistence in Docker Volume

- src/ubuntu/NOTES.md
Closes https://github.com/devcontainers/templates/issues/127
> Ubuntu: Remove incorrect information

- .github/workflows/update-documentation.yml
Fixes action failures - https://github.com/devcontainers/templates/actions/runs/4236328821/jobs/7361021749#step:4:49
> "Update Documentation" workflow - use gh api to create a documentation PR

- src/ubuntu/README.md
Automated documentation update
> Automated documentation update

- src/ruby-rails-postgres/devcontainer-template.json
- src/ruby/devcontainer-template.json
Ref: https://www.ruby-lang.org/en/downloads/branches/ and https://github.com/devcontainers/images/issues/447
> EOL - ruby 2.7

- src/javascript-node-mongo/devcontainer-template.json
- src/javascript-node-postgres/devcontainer-template.json
- src/javascript-node/devcontainer-template.json
Ref: https://github.com/devcontainers/images/issues/446
> Update javascript-node Templates with imageVariant:20

- src/typescript-node/devcontainer-template.json
Ref: https://github.com/devcontainers/images/pull/532
> Update typescript-node Templates with imageVariant:20

- src/javascript-node-mongo/devcontainer-template.json
- src/javascript-node/devcontainer-template.json
- src/typescript-node/devcontainer-template.json
Ref: https://github.com/devcontainers/images/issues/445
> EOL - Node 14

- src/alpine/devcontainer-template.json
Ref: https://github.com/devcontainers/images/issues/443
> EOL - Alpine 3.14

- src/alpine/devcontainer-template.json
Ref: https://github.com/devcontainers/images/issues/574
> Templates: Add support for alpine 3.18

- src/debian/devcontainer-template.json
- test/test-utils/test-utils.sh
Ref: https://github.com/devcontainers/images/commit/e90321f71d69348675c1b463b2e350b50ff6e960 & https://github.com/devcontainers/images/issues/582
https://www.debian.org/News/2023/20230610 🎉
> Debian template - Adds support for bookworm

- src/cpp-mariadb/.devcontainer/Dockerfile
- src/cpp-mariadb/devcontainer-template.json
- src/cpp/.devcontainer/Dockerfile
- src/cpp/devcontainer-template.json
- src/debian/devcontainer-template.json
- src/java-postgres/.devcontainer/Dockerfile
- src/java-postgres/devcontainer-template.json
- src/java/.devcontainer/devcontainer.json
- src/java/devcontainer-template.json
Ref: https://github.com/devcontainers/images/issues/614
> Cpp & java Templates: Add debian:bookworm options & remove the ones without OS bit

- src/postgres/.devcontainer/Dockerfile
- src/postgres/devcontainer-template.json
- src/python/.devcontainer/devcontainer.json
- src/python/devcontainer-template.json
Ref: https://github.com/devcontainers/images/issues/622
> Python Template: Add debian:bookworm options & remove the ones without OS bit

- src/rust-postgres/.devcontainer/Dockerfile
- src/rust-postgres/devcontainer-template.json
- src/rust/.devcontainer/devcontainer.json
- src/rust/devcontainer-template.json
Ref: https://github.com/devcontainers/images/issues/617
> Rust Templates: Add debian:bookworm options

- src/ruby-rails-postgres/.devcontainer/Dockerfile
- src/ruby-rails-postgres/devcontainer-template.json
- src/ruby/.devcontainer/devcontainer.json
- src/ruby/devcontainer-template.json
Ref: https://github.com/devcontainers/images/issues/609
> Ruby Templates: Add debian:bookworm options & remove the ones without OS bit

- src/postgres/devcontainer-template.json
- src/python/devcontainer-template.json
Ref: https://github.com/devcontainers/images/issues/590 & https://github.com/devcontainers/images/pull/642
> Python Templates: python 3.7 EOL

- src/php-mariadb/.devcontainer/Dockerfile
- src/php-mariadb/devcontainer-template.json
- src/php/.devcontainer/devcontainer.json
- src/php/devcontainer-template.json
Ref: https://github.com/devcontainers/images/issues/615
> PHP Templates: Add debian:bookworm options & remove the ones without OS bit

- src/jekyll/.devcontainer/devcontainer.json
- src/jekyll/devcontainer-template.json
Ref: https://github.com/devcontainers/images/issues/620
> Jekyll Template: Add bookworm variant option

- src/go-postgres/.devcontainer/Dockerfile
- src/go-postgres/devcontainer-template.json
- src/go/.devcontainer/devcontainer.json
- src/go/devcontainer-template.json
Ref: https://github.com/devcontainers/images/issues/613
> Go Templates: Add debian:bookworm options & remove the ones without OS bit

- src/javascript-node-mongo/devcontainer-template.json
- src/javascript-node-postgres/devcontainer-template.json
- src/javascript-node/devcontainer-template.json
- src/typescript-node/devcontainer-template.json
Ref: https://github.com/devcontainers/images/issues/749 & https://github.com/nodejs/release#release-schedule & https://nodejs.org/en/blog/announcements/nodejs16-eol
> [EOL] Node 16 - Updates template proposals

- src/ruby-rails-postgres/.devcontainer/Dockerfile
- src/ruby-rails-postgres/devcontainer-template.json
- test/ruby-rails-postgres/test.sh
Updated the line to install the Rails gem to use the vscode user. This
brings it in line with the optional line to install node packages. Also
updated the example line for additional gems.
> Use vscode user to install gems.

- src/java-postgres/devcontainer-template.json
- src/java/devcontainer-template.json
Ref: https://github.com/devcontainers/images/issues/748
> Java - Adds support for 21

- src/dotnet-fsharp/.devcontainer/devcontainer.json
- src/dotnet-fsharp/devcontainer-template.json
- src/dotnet-mssql/.devcontainer/Dockerfile
- src/dotnet-mssql/devcontainer-template.json
- src/dotnet-postgres/.devcontainer/Dockerfile
- src/dotnet-postgres/devcontainer-template.json
- src/dotnet/.devcontainer/devcontainer.json
- src/dotnet/devcontainer-template.json
- src/javascript-node-mongo/.devcontainer/Dockerfile
- src/javascript-node-mongo/devcontainer-template.json
Ref: https://github.com/devcontainers/images/issues/607 and https://github.com/devcontainers/images/pull/809
> Re-pin images with new major versions (Dotnet)

- src/python/devcontainer-template.json
Ref: https://github.com/devcontainers/images/issues/750
> [Templates] Support python 3.12.0

- src/alpine/devcontainer-template.json
Ref: https://github.com/devcontainers/images/issues/785
>  EOL Alpine 3.15

- src/dotnet-fsharp/.devcontainer/devcontainer.json
- src/dotnet-fsharp/devcontainer-template.json
- src/dotnet-mssql/devcontainer-template.json
- src/dotnet-postgres/devcontainer-template.json
- src/dotnet/devcontainer-template.json
Ref: https://github.com/devcontainers/images/issues/787
> [.NET Templates]: Support .NET 8.0

- src/alpine/devcontainer-template.json
- src/php-mariadb/devcontainer-template.json
- src/php/devcontainer-template.json
- src/ruby-rails-postgres/devcontainer-template.json
- src/ruby/devcontainer-template.json
- test/alpine/test-utils-alpine.sh
Ref: 
- https://github.com/devcontainers/images/issues/827
- https://github.com/devcontainers/images/issues/786
- https://github.com/devcontainers/images/issues/866
> [Php, Ruby, Alpine] EOL/New version updates

- src/go-postgres/devcontainer-template.json
- src/go/devcontainer-template.json
Ref: https://github.com/devcontainers/images/issues/943 and https://github.com/devcontainers/images/issues/944
> Go : Add support for 1.22 ; EOL 1.20

- .github/dependabot.yml
- README.md
Closes: https://github.com/devcontainers/templates/issues/237
Updated the README to avoid confusions on to how to use the Templates
> Update README with "How to use Templates" section

- src/ubuntu/devcontainer-template.json
**Template name**:
* Ubuntu
**Description**:
This PR makes the following changes :
* `Ubuntu 24.04 noble` released and supported now in `Ubuntu` template
**Checklist**:
> ubuntu-24.04-noble release changes

- src/alpine/README.md
- src/alpine/devcontainer-template.json
**Template Name**
* Alpine
**Description**
This PR achieves the following: 
* Alpine 3.16 EOL changes have been implemented
> Alpine - Support 3.20 & EOL 3.16

- src/anaconda-postgres/.devcontainer/Dockerfile
- src/anaconda-postgres/devcontainer-template.json
- src/anaconda/.devcontainer/Dockerfile
- src/anaconda/devcontainer-template.json
**Template Name**
* Anaconda
**Description**
* This PR changes the `major version` number for `anaconda's` template
**_changelog_**
Updated `Dockerfile` for `Anaconda's` template
> [anaconda] - bookworm released changes

- src/cpp-mariadb/devcontainer-template.json
- src/cpp/devcontainer-template.json
**Template Name**
*CPP
**Changes**
*Buster - EOL - changes
> [cpp]- buster eol changes

- src/dotnet-mssql/devcontainer-template.json
- src/dotnet-postgres/devcontainer-template.json
- src/dotnet/devcontainer-template.json
**Template Name**
* dotnet, dotnet-mssql, dotnet-postgres
**_Changelog_**
* added `ubuntu-noble` variant to the list of supported variants
**Checklist**
> [dotnet] - ubuntu-noble - addition

- src/php-mariadb/devcontainer-template.json
- src/php/devcontainer-template.json
Ref: https://github.com/devcontainers/images/issues/90
> EOL PHP 8.1

- src/dotnet-mssql/devcontainer-template.json
- src/dotnet-postgres/devcontainer-template.json
- src/dotnet/devcontainer-template.json
**Ref:** [Issue](https://github.com/devcontainers/internal/issues/236)
> EOL dotnet 6.0 version bump

- src/alpine/devcontainer-template.json
**Ref:** [Issue](https://github.com/devcontainers/internal/issues/237)
> EOL Alpine 3.17 version bump

- src/php-mariadb/devcontainer-template.json
- src/php/devcontainer-template.json
**Ref:** [Issue](https://github.com/devcontainers/internal/issues/238)
> EOL PHP 8.1 version bump

- src/alpine/README.md
- src/alpine/devcontainer-template.json
**Ref**: https://github.com/devcontainers/images/issues/90
> Add Alpine 3.21

- src/dotnet-mssql/devcontainer-template.json
- src/dotnet-postgres/devcontainer-template.json
- src/dotnet/devcontainer-template.json
**Ref:** [Issue](https://github.com/devcontainers/internal/issues/257) 
**Note:** The latest tags aren't pinned to the 10.0-preview version.
> Support dotnet 10.0-preview version
